core/urls.py
from django.urls import path
from . import views

app_name='core'
urlpatterns = [
    path('', views.home, name='home'),
    path('cadastro', views.cadastro, name='cadastro'),

]

sistema/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('core.urls', namespace='core')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def home(request):
	return render(request, 'home.html')

def cadastro(request):
	return render(request, 'cadastro.html')	

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="{% static 'css/bootstrap4.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/login.css' %}">
	<title>Sistema</title>
</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>

core/templates/cadastro.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
	
  	<form class="form-signin">

		<h3 class="form-signin-heading">Abra uma conta.</h3>
  		<div class="form-group">
        	<label for="inputNome">Nome</label>
        	<input type="text" id="inputNome" class="form-control" placeholder="Nome completo" autofocus>
        </div>
		<div class="form-group">        
        	<label for="inputEmail">Email</label>
        	<input type="email" id="inputEmail" class="form-control" placeholder="Email" autofocus>
        </div>
		<div class="form-group">
        	<label for="inputPassword">Nova senha</label>
        	<input type="password" id="inputPassword" class="form-control" placeholder="Nova senha">
        </div>
		<div class="form-group">		
			<label for="inputData">Data de Nascimento</label>
        	<input type="date" id="inputData" class="form-control" placeholder="Data de Nascimento"autofocus>
        </div>

		<fieldset class="form-group">
    	<div class="form-check">
      		<label class="form-check-label">
        	<input type="radio" class="form-check-input" name="inputSexo" id="inputFem" value="Feminino"> Feminino</label>
    	
			<label class="form-check-label float-right">
			<input type="radio" class="form-check-input" name="inputSexo" id="inputMasc" value="Masculino"> Masculino</label>
		</div>
		</fieldset>
    	<button class="btn btn-lg btn-primary btn-block" type="submit">Cadastrar</button>
    	<a href="{% url 'core:home' %}">Voltar</a>
    	
	</form>

</div>

{% endblock %}

core/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

  	<form class="form-signin">
        <h2 class="form-signin-heading">Login</h2>
        <label for="inputEmail" class="sr-only">E-mail</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Endereço de e-mail" required autofocus>
        <label for="inputPassword" class="sr-only">Senha</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Senha" required>
    	<button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
    	<div class="form-group row">
        	<small class="form-text col-5"><a href="{% url 'core:cadastro' %}">Cadastre-se</a></small>
        	<small class="form-text col-7"><a href="#">Esqueceu a senha?</a></small>
        </div>
	</form>

</div>
{% endblock %}